package day07

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class MainTest {
    @Nested
    inner class GetNumberOfSplitsTest {
        @Test
        fun `acceptance test based on known input and output`() {
            val input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
            """.trimIndent()
            val numberOfSplits = getNumberOfSplits(input)
            numberOfSplits shouldBe 21
        }
    }

    @Test
    fun `get starting position`() {
        val input = """
            .......S.......
        """.trimIndent()
        val startingPosition = getStartingPosition(input)
        startingPosition shouldBe 7
    }
}